name: FDPhotoAlbum 
options: 
  createIntermediateGroups: true 
  indentWidth: 4 
  tabWidth: 4 
  bundleIdPrefix: "com.nio"
targets: 
  FDPhotoAlbum:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: FDPhotoAlbum
